// REDUX ACTION TYPES
export const SIGN_IN = "SIGN_IN";
export const SIGN_IN_SUCCESS = "SIGN_IN_SUCCESS";
export const SIGN_OUT = "SIGN_OUT";
export const SIGN_UP = "SIGN_UP";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";

//REFERRAL AND WALLET RELATED ACTION TYPES
export const IS_USER_USED_REFERRAL_CODE = 'IS_USER_USED_REFERRAL_CODE'
export const ADD_REFERRAL_INFO = 'ADD_REFERRAL_INFO'
export const UPDATE_CURRENT_REFEREE = 'UPDATE_CURRENT_REFEREE'

// PROFILE RELATED ACTION TYPES
export const PROFILE_FETCH_SUCCESS = "PROFILE_FETCH_SUCCESS";

// ADDRESS RELATED ACTION TYPES
export const ADD_OR_UPDATE_ADDRESS = "ADD_OR_UPDATE_ADDRESS";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const SET_PRIMARY_ADDRESS = "SET_PRIMARY_ADDRESS";

// CONTACT RELATED ACTION TYPES
export const ADD_OR_UPDATE_CONTACT = "ADD_OR_UPDATE_CONTACT";
export const DELETE_CONTACT = "DELETE_CONTACT";
export const SET_PRIMARY_CONTACT = "SET_PRIMARY_CONTACT";
export const SET_USER_NAME = 'SET_USER_NAME'

export const SET_IS_ORDER_REVIEW_SHOW = 'SET_IS_ORDER_REVIEW_SHOW'

export const REQUESTED_VARIANT_ID = "REQUESTED_VARIANT_ID"
export const REMOVE_REQUESTED_VARIANT_ID = "REQUESTED_VARIANT_ID"