// REDUX ACTION TYPES
export const PLACE_ORDER = "PLACE_ORDER";
export const PLACE_ORDER_NOTES = 'PLACE_ORDER_NOTES'
export const ADD_NEW_ORDER_ITEMS = 'ADD_NEW_ORDER_ITEMS'
export const REMOVE_NEW_ORDER_ITEM = 'REMOVE_NEW_ORDER_ITEM'